<a href="https://colab.research.google.com/github/sagunkayastha/CAI_Workshop/blob/main/Workshop_1/intro_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics

- Numpy is the core library for scientific computing in python.
- It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [37]:
import numpy as np

In [38]:
a = np.array([1,2,3])

In [39]:
print (a)

[1 2 3]


In [40]:
print (type(a))

<class 'numpy.ndarray'>


ndarray -> n-dimensional array

In [41]:
a.shape

(3,)

#### minimum dimensions

In [42]:
b = np.array([1,2,3,4,5,6], ndmin=2)
print (b)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [43]:
b.shape

(1, 6)

#### Multidimension

In [44]:
c = np.array( [ [1,2], [3,4] ] )
print ("The numpy array is :\n ", c)
print ("The type of the object is  :", type(c))
print ("The shape of the object is :", c.shape)

The numpy array is :
  [[1 2]
 [3 4]]
The type of the object is  : <class 'numpy.ndarray'>
The shape of the object is : (2, 2)


- Inner elements

In [45]:
c0 = c[0]
print ("The first object in the numpy array is: ", c0)
print ("The type of the first object is       :", type(c0))
print ("The shape of the first object is      :", c0.shape)

The first object in the numpy array is:  [1 2]
The type of the first object is       : <class 'numpy.ndarray'>
The shape of the first object is      : (2,)


- individual elements of an array

In [46]:
c00 = c[0][0]
print ("The first scalar element of the array: ", c00)
print ("The type of the scalar element       : ", type(c00))

The first scalar element of the array:  1
The type of the scalar element       :  <class 'numpy.int32'>


#### Directly checking the datatype of elements

In [47]:
c.dtype

dtype('int32')

#### This means the items in the numpy array are 64-bit integers
<br>
Lets create an array that contains elements with 8-bit unsigned integers

In [48]:
d = np.array( [ [1,2], [3,4] ], dtype='uint8' )
print (d)

[[1 2]
 [3 4]]


In [49]:
type(d[0][0])

numpy.uint8

#### For further details on different numpy types, refer to <br>
https://www.numpy.org/devdocs/user/basics.types.html

### Some easy methods of creating numpy arrays

In [50]:
a = np.zeros((2,2))
print (a)

[[0. 0.]
 [0. 0.]]


In [51]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [52]:
a = np.full((2,2), 10)
print (a)

[[10 10]
 [10 10]]


#### random matrix

In [53]:
a = np.random.random((2,2))
print (a)

[[0.32366351 0.73375001]
 [0.77869367 0.95544484]]


#### np.arange

In [54]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
a = np.arange(1, 10, dtype=float)
print (a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [56]:
a = np.arange(1, 10, 0.5) # start, end, step
print (a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [57]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

#### Creating equally spaced elements in a particular range

In [58]:
a = np.linspace(1.0, 6.0, 11) # start, end, num-points
print (a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]


In [59]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

#### Random matrix

In [60]:
a = np.random.random((3,3))
print (a)

[[0.33546814 0.03183867 0.44467045]
 [0.83637542 0.36435685 0.93624332]
 [0.40156988 0.81926322 0.32854592]]


### Some basic operations on numpy array

#### Maximum value in the array

In [61]:
a.max()

0.936243320717097

#### Minimum value in the array

In [62]:
a.min()

0.03183866546677028

#### Index of maximum value in the array

In [63]:
a.argmax()

5

#### Index of minimum value in the array

In [64]:
a.argmin()

1

### Array Indexing and Slicing

In [65]:
a = np.random.random((4, 4, 3))
print (a)

[[[0.48673723 0.48856396 0.16555082]
  [0.48392283 0.23577774 0.95616448]
  [0.5029426  0.94409545 0.48575868]
  [0.11324179 0.4704656  0.0107861 ]]

 [[0.23602614 0.18505265 0.24260297]
  [0.06762163 0.44099026 0.86237151]
  [0.18618471 0.95443587 0.11963248]
  [0.55162451 0.86915083 0.99839142]]

 [[0.32300782 0.16249115 0.51144438]
  [0.50702716 0.14116721 0.54929332]
  [0.64736333 0.15175001 0.98073981]
  [0.78015646 0.51893526 0.33915627]]

 [[0.86322663 0.4844668  0.51810126]
  [0.35189766 0.45352266 0.9818967 ]
  [0.68790053 0.61629499 0.48751944]
  [0.44719058 0.65313315 0.698639  ]]]


#### Try out more slices in the following cells

### Array Math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy moudle

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print ("x : \n", x)
print ("y : \n", y)

#### Elementwise sum

In [ ]:
x + y

In [ ]:
np.add(x,y)

#### Elementwise difference

In [ ]:
x - y

In [ ]:
np.subtract(x,y)

#### Elementwise product

In [ ]:
x * y

In [ ]:
np.multiply(x,y)

#### Elementwise division

In [ ]:
x / y

In [ ]:
np.divide(x,y)

#### Elementwise square root

In [ ]:
np.sqrt(x)

#### Matrix Multiplication


In [ ]:
np.dot(x,y)

In [ ]:
x.dot(y)

In [ ]:
y.dot(x)

### Sum

In [ ]:
np.sum(x)

##### Column wise sum

In [ ]:
np.sum(x, axis=0)

##### Row wise sum

In [ ]:
np.sum(x, axis=1)

### Creating arrays like...

In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print (a)

In [ ]:
b = np.ones_like(a)
print (b)

##### Prototype array and the created arrays will have the elements of same datatype

In [ ]:
print (a.dtype)
print (b.dtype)

In [ ]:
c = np.zeros_like(a)
print (c)

In [ ]:
d = np.empty_like(a)
print (d)

##### Filling data in the empty array

In [ ]:
e = np.full_like(a, 5)
print (e)

#### Reshaping an array

In [ ]:
f = np.reshape(e, (2,4))
print (f)

###### Try the following reshape

In [ ]:
g = np.reshape(f, (5,3))

##### Read the error traceback and find out why the error occured

##### Logical operations on array

In [ ]:
a = np.arange(5,10)
print(a)
bool_a = a > 7
print (bool_a)

In [ ]:
new_a = a[bool_a]

In [ ]:
new_a

##### What we did here is we created a new array from array a containing only the values greater than 7.
Doing this in single line

In [ ]:
a = np.arange(5,10)
new_a = a[a>7]

In [ ]:
new_a

### Few more operations on numpy array

##### square root

In [ ]:
np.sqrt(a)

##### exponent

In [ ]:
np.exp(a)

##### sine

In [ ]:
np.sin(a)

##### consine

In [ ]:
np.cos(a)

##### log

In [ ]:
np.log(a)

##### Standard deviation

In [ ]:
np.std(a)