<a href="https://colab.research.google.com/github/sagunkayastha/CAI_Workshop/blob/main/Workshop_1/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic python

#### Basic Keyboard Shortcuts
- `Shift + Enter` to run cell
- `Escape` to leave cell
- `a` to add a cell above
- `b` to add a cell below
- `dd` to delete a cell
- `m` to change cell to Markdown (after pressing escape)
- `y` to change cell to Code (after pressing escape)
- Arrow keys move cells (after pressing escape)
- `Enter` to enter cell   


---

#### Getting Help
- add question mark to end of object
- use help(*)

In [38]:
list?

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, _Threads, ConvertingList, DeferredConfigList, _ymd, SList, _ImmutableLineList, FormattedText, NodeList, ...

In [39]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [40]:
# Example for strings, float, and int

# Strings
string_variable = "Hello, World!"

# Float
float_variable = 3.14

# Int
int_variable = 42


In [41]:
# Example of list indexing

list_variable = [1, 2, 3, "four", 5.0]

# Accessing the first element of the list
first_element = list_variable[0]
print(first_element)  # Output: 1

# Accessing the last element of the list
last_element = list_variable[-1]
print(last_element)  # Output: 5.0

# Accessing a range of elements in the list
range_of_elements = list_variable[1:4]
print(range_of_elements)  # Output: [2, 3, 'four']

# Modifying an element in the list
list_variable[3] = "FOUR"
print(list_variable)  # Output: [1, 2, 3, 'FOUR', 5.0]

# Adding an element to the end of the list
list_variable.append("six")
print(list_variable)  # Output: [1, 2, 3, 'FOUR', 5.0, 'six']

# Removing an element from the list
list_variable.remove(2)
print(list_variable)  # Output: [1, 3, 'FOUR', 5.0, 'six']

1
5.0
[2, 3, 'four']
[1, 2, 3, 'FOUR', 5.0]
[1, 2, 3, 'FOUR', 5.0, 'six']
[1, 3, 'FOUR', 5.0, 'six']


In [42]:
# Example of dictionary indexing

dict_variable = {"name": "John", "age": 30, "city": "New York"}

# Accessing a value by key
name_value = dict_variable["name"]
print(name_value)  # Output: John

# Modifying a value by key
dict_variable["age"] = 31
print(dict_variable)  # Output: {'name': 'John', 'age': 31, 'city': 'New York'}

# Adding a new key-value pair
dict_variable["country"] = "USA"
print(dict_variable)  # Output: {'name': 'John', 'age': 31, 'city': 'New York', 'country': 'USA'}

# Removing a key-value pair
del dict_variable["city"]
print(dict_variable)  # Output: {'name': 'John', 'age': 31, 'country': 'USA'}

John
{'name': 'John', 'age': 31, 'city': 'New York'}
{'name': 'John', 'age': 31, 'city': 'New York', 'country': 'USA'}
{'name': 'John', 'age': 31, 'country': 'USA'}


In [43]:
# Example of conditional statements and loops

# If statement
x = 5
if x > 0:
    print("x is positive")
elif x == 0:
    print("x is zero")
else:
    print("x is negative")

# While loop
i = 0
while i < 5:
    print(i)
    i += 1

# For loop
for i in range(5):
    print(i)

# Nested loops
for i in range(3):
    for j in range(2):
        print(i, j)



x is positive
0
1
2
3
4
0
1
2
3
4
0 0
0 1
1 0
1 1
2 0
2 1


In [44]:
# Example of array indexing
loop_var = [100,200,300,400,500]
# we will use enumerate to get the index and value of the list
for i, var in enumerate(loop_var):
    print(i, var)

0 100
1 200
2 300
3 400
4 500


In [45]:
# Define a function to add two numbers
def add_numbers(x, y):
    return x + y

result = add_numbers(3, 5)
print(result)

# Define a function with a default value for an argument
def add_numbers(x, y=10):
    return x+y

result = add_numbers(3)
print(result)
result = add_numbers(3,5)
print(result)

8
13
8


## Numpy

In [46]:
import numpy as np

In [47]:
# Create a numpy array
a = np.array([1,2,3])
print (a)
print (type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [48]:
a[0]

1

In [49]:
# Create a 2D numpy array
c = np.array( [ [1,2], [3,4] ] )
print ("The numpy array is :\n ", c)
print ("The type of the object is  :", type(c))
print ("The shape of the object is :", c.shape)

The numpy array is :
  [[1 2]
 [3 4]]
The type of the object is  : <class 'numpy.ndarray'>
The shape of the object is : (2, 2)


In [50]:
# Accessing the first object in the numpy array
c0 = c[0]
print ("The first object in the numpy array is: ", c0)
print ("The type of the first object is       :", type(c0))
print ("The shape of the first object is      :", c0.shape)

The first object in the numpy array is:  [1 2]
The type of the first object is       : <class 'numpy.ndarray'>
The shape of the first object is      : (2,)


In [51]:
# Accessing the first scalar element of the array
c00 = c[0][0]
print ("The first scalar element of the array: ", c00)
print ("The type of the scalar element       : ", type(c00))

The first scalar element of the array:  1
The type of the scalar element       :  <class 'numpy.int32'>


In [52]:
# Accessing the second scalar element of the array
d = np.array( [ [1,2], [3,4] ], dtype='uint8' )
print (d)

[[1 2]
 [3 4]]


In [53]:
# Create a random numpy array
a = np.random.random((2,2))
print (a)

[[0.73021986 0.79469719]
 [0.0509703  0.1571476 ]]


In [54]:
# Using arange to create a numpy array, 
a = np.arange(1, 10, 0.5) # start, end, step
print (a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [55]:
# Using linspace to create a numpy array, 
a = np.linspace(1.0, 6.0, 11) # start, end, num-points
print (a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]


In [56]:
# find the min and max of the array
a.min(),  a.max(), a.argmax()

(1.0, 6.0, 10)

### Array Math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy moudle

In [57]:
# Creating two numpy arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print ("x : \n", x)
print ("y : \n", y)

x : 
 [[1. 2.]
 [3. 4.]]
y : 
 [[5. 6.]
 [7. 8.]]


In [58]:
# using the + operator and np.add to add the two arrays
np.add(x,y) 
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [59]:
# using the - operator and np.subtract to subtract the two arrays
np.sqrt(x)
# using the * operator and np.multiply to multiply the two arrays
np.dot(x,y)

array([[19., 22.],
       [43., 50.]])

In [60]:
# creating a numpy array of shape (5,5) with random values
arr = np.random.random((5,5))
arr

array([[0.42564582, 0.2151458 , 0.24627383, 0.80482403, 0.71388384],
       [0.4422747 , 0.78443323, 0.49659215, 0.21289006, 0.60799693],
       [0.62406331, 0.98768031, 0.55080687, 0.17582894, 0.18815458],
       [0.7129944 , 0.68421928, 0.13134463, 0.71570256, 0.92331277],
       [0.413302  , 0.07945783, 0.33217926, 0.40929441, 0.17592446]])

In [61]:
# reshaping the array to (1,25)
arr2 = np.reshape(arr, (1,25))
arr2

array([[0.42564582, 0.2151458 , 0.24627383, 0.80482403, 0.71388384,
        0.4422747 , 0.78443323, 0.49659215, 0.21289006, 0.60799693,
        0.62406331, 0.98768031, 0.55080687, 0.17582894, 0.18815458,
        0.7129944 , 0.68421928, 0.13134463, 0.71570256, 0.92331277,
        0.413302  , 0.07945783, 0.33217926, 0.40929441, 0.17592446]])

In [62]:

a = np.arange(5,10)
print(a)
bool_a = a > 7
print (bool_a)

[5 6 7 8 9]
[False False False  True  True]


## Virtual Environment and Conda environment

Virtual environments and Conda environments provide a way to manage project-specific dependencies and isolate them from the system-wide Python installation.

 Virtual environments are Python-specific and can be created using tools like virtualenv or venv, while Conda is a more comprehensive package and environment management system that can handle packages from multiple languages. Conda is particularly useful for data science and scientific computing projects.

## Create a virtual environment named "myenv"
python -m venv myenv

myenv\Scripts\activate

source myenv/bin/activate

pip install numpy

deactivate


## Create a Conda environment:
conda create --name mycondaenv python=3.7

conda activate mycondaenv

conda install numpy

conda deactivate


**Conda is a versatile choice for complex projects with diverse dependencies, while virtualenv is a lightweight option for Python-specific environments. Consider your project's requirements and the broader ecosystem in which you're working when making your decision.**

In [63]:
# Define the list of packages and their versions
packages = [
    "matplotlib==3.1.1",
    "requests==2.22.0",
    "pandas==0.25.3",
    "seaborn==0.9.0",
    "numpy==1.17.4",
    "ipython==7.10.1",
    "beautifulsoup4==4.8.1",
    "graphviz==0.13.2",
    "mlxtend==0.17.0",
    "watermark==2.0.2",
    "scikit-learn==0.22",
    "ipython-sql==0.3.9",
    "joblib==0.14.1"
]

# Specify the name of the output file
output_file = "requirements.txt"

# Write the package names and versions to the requirements.txt file
with open(output_file, "w") as f:
    for package in packages:
        f.write(package + "\n")

print(f"Requirements written to {output_file}")


Requirements written to requirements.txt


In [64]:
import yaml

# Define the YAML configuration
yaml_config = """
name: myenv
channels:
  - defaults
dependencies:
  - python=3.7   # Specify the Python version
  - matplotlib=3.1.1
  - requests=2.22.0
  - pandas=0.25.3
  - seaborn=0.9.0
  - numpy=1.17.4
  - ipython=7.10.1
  - beautifulsoup4=4.8.1
  - graphviz=0.13.2
  - mlxtend=0.17.0
  - watermark=2.0.2
  - scikit-learn=0.22
  - ipython-sql=0.3.9
  - joblib=0.14.1

"""

# Specify the name of the output YAML file
output_file = "myenv.yml"

# Write the YAML configuration to the file
with open(output_file, "w") as f:
    f.write(yaml_config)

print(f"YAML configuration written to {output_file}")


YAML configuration written to myenv.yml


pip install -r requirement.txt

or

conda env create -f myenv.yml

--------------------------------

## Magic Function
The percent signs, % and %%, are one of the basic features of Jupyter Notebook
and are called magic commands. Magic commands starting with %% will apply to
the entire cell, while magic commands starting with % will only apply to that line.

In [65]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [66]:
%mkdir test

A subdirectory or file test already exists.


In [67]:

%$%time
import numpy as np

# Create a large array of random numbers
a = np.random.rand(int(1e7))

# Get runtime for the entire cell

# Calculate the square root of each element in the array
for i in range(len(a)):
    a[i] = np.sqrt(a[i])


UsageError: Line magic function `%$%time` not found.


In [68]:
# Get runtime for one line
%time a = [np.sqrt(_a) for _a in a]
"""CPU time measures the actual time the CPU spends executing code, while wall time includes all time elapsed from the program's start to its completion, including time spent waiting for external resources or system-related delays.

"""

CPU times: total: 0 ns
Wall time: 0 ns


"CPU time measures the actual time the CPU spends executing code, while wall time includes all time elapsed from the program's start to its completion, including time spent waiting for external resources or system-related delays.\n\n"

In [69]:
%%bash

echo "using bash from inside Jupyter!" > test-file.txt
ls
echo ""
cat test-file.txt
# rm test-file.txt

lease enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization


CalledProcessError: Command 'b'\necho "using bash from inside Jupyter!" > test-file.txt\nls\necho ""\ncat test-file.txt\n# rm test-file.txt\n'' returned non-zero exit status 1.

In [1]:


class Calculator:
    
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def add(self):
        return self.a + self.b
    
    
    
    def call(loop_var):
        # ask input
        # if exit loop_var false
        
Calculator()
obj = Calculator(3, 5)
loop_var = True
while loop_var == True
    obj.call()

I am called
